import { ResEntity } from './types/ResEntity.js';
import { ResIdentItem } from './types/ResIdentItem.js';

export const DEMO_OVERVIEW: ResEntity = {
  count: 23,
  Items: [
    { name: '#', icon: 'svgFolderOpen', type: 'g_1_[#]' },
    { name: 'A', icon: 'svgFolderOpen', type: 'g_1_[A]' },
    { name: 'B', icon: 'svgFolderOpen', type: 'g_1_[B]' },
    { name: 'C', icon: 'svgFolderOpen', type: 'g_1_[C]' },
    { name: 'D', icon: 'svgFolderOpen', type: 'g_1_[D]' },
    { name: 'E', icon: 'svgFolderOpen', type: 'g_1_[E]' },
    { name: 'F', icon: 'svgFolderOpen', type: 'g_1_[F]' },
    { name: 'G', icon: 'svgFolderOpen', type: 'g_1_[G]' },
    { name: 'H', icon: 'svgFolderOpen', type: 'g_1_[H]' },
    { name: 'J', icon: 'svgFolderOpen', type: 'g_1_[J]' },
    { name: 'K', icon: 'svgFolderOpen', type: 'g_1_[K]' },
    { name: 'L', icon: 'svgFolderOpen', type: 'g_1_[L]' },
    { name: 'M', icon: 'svgFolderOpen', type: 'g_1_[M]' },
    { name: 'N', icon: 'svgFolderOpen', type: 'g_1_[N]' },
    { name: 'O', icon: 'svgFolderOpen', type: 'g_1_[O]' },
    { name: 'P', icon: 'svgFolderOpen', type: 'g_1_[P]' },
    { name: 'R', icon: 'svgFolderOpen', type: 'g_1_[R]' },
    { name: 'S', icon: 'svgFolderOpen', type: 'g_1_[S]' },
    { name: 'T', icon: 'svgFolderOpen', type: 'g_1_[T]' },
    { name: 'U', icon: 'svgFolderOpen', type: 'g_1_[U]' },
    { name: 'V', icon: 'svgFolderOpen', type: 'g_1_[V]' },
    { name: 'Y', icon: 'svgFolderOpen', type: 'g_1_[Y]' },
    { name: 'Z', icon: 'svgFolderOpen', type: 'g_1_[Z]' },
  ],
};

export const DEMO_DETAILS: ResEntity<ResIdentItem>[] = [
  {
    count: 4,
    Items: [
      {
        type: 'i_1',
        name: '_Administrator_ - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 1,
      },
      { type: 'i_126', name: '000000a1', icon: 'svgCard', hasUser: true, userId: 216 },
      { type: 'i_146', name: '000000ad', icon: 'svgCard', hasUser: true, userId: 223 },
      { type: 'i_14', name: '000000c8', icon: 'svgCard', hasUser: true, userId: 1 },
    ],
  },
  {
    count: 6,
    Items: [
      {
        type: 'i_25',
        name: 'Achim Oberlaend - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 13,
      },
      {
        type: 'i_24',
        name: 'Alexander Zeiß - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 18,
      },
      {
        type: 'i_31',
        name: 'Alina Grewe - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 19,
      },
      {
        type: 'i_33',
        name: 'Anne Koch - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 27,
      },
      {
        type: 'i_34',
        name: 'Annika Pöstges - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 28,
      },
      {
        type: 'i_32',
        name: 'Arne Pöstges - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 29,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_85',
        name: 'Benjamin Rees - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 34,
      },
    ],
  },
  {
    count: 8,
    Items: [
      {
        type: 'i_92',
        name: 'Calvin Pauls - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 36,
      },
      {
        type: 'i_42',
        name: 'Camilla-Sophie - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 37,
      },
      {
        type: 'i_41',
        name: 'Caro Strewginsk - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 38,
      },
      {
        type: 'i_43',
        name: 'Christian Smuda - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 43,
      },
      {
        type: 'i_44',
        name: 'Christina Wolff - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 45,
      },
      {
        type: 'i_40',
        name: 'Claudia Henke - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 47,
      },
      {
        type: 'i_37',
        name: 'Cordula Zeiß - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 48,
      },
      {
        type: 'i_39',
        name: 'Cornelia Pauls - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 49,
      },
    ],
  },
  {
    count: 2,
    Items: [
      {
        type: 'i_147',
        name: 'Dana Smolny - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 226,
      },
      {
        type: 'i_179',
        name: 'Dennis Rosowski - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 239,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_36',
        name: 'Ede Aliji - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 53,
      },
    ],
  },
  {
    count: 4,
    Items: [
      {
        type: 'i_47',
        name: 'Fabian Simons - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 63,
      },
      {
        type: 'i_49',
        name: 'Fabian Solovera - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 64,
      },
      {
        type: 'i_156',
        name: 'Felix Sund - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 228,
      },
      {
        type: 'i_56',
        name: 'Franziska Kleme - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 66,
      },
    ],
  },
  {
    count: 3,
    Items: [
      {
        type: 'i_10',
        name: 'Getränkeliefera - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 10,
      },
      {
        type: 'i_66',
        name: 'Gina Kleinholz - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 69,
      },
      {
        type: 'i_50',
        name: 'Gotlind Pöstges - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 70,
      },
    ],
  },
  {
    count: 4,
    Items: [
      {
        type: 'i_52',
        name: 'Hartmut Henke - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 72,
      },
      {
        type: 'i_46',
        name: 'Heike Kleinholz - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 73,
      },
      {
        type: 'i_48',
        name: 'Henry Reimer - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 74,
      },
      {
        type: 'i_67',
        name: 'Herbert Breitin - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 75,
      },
    ],
  },
  {
    count: 12,
    Items: [
      {
        type: 'i_164',
        name: 'Jacqueline Völkel - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 232,
      },
      {
        type: 'i_51',
        name: 'Jakob Adolf - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 199,
      },
      {
        type: 'i_15',
        name: 'Jan Pöstges - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 82,
      },
      {
        type: 'i_20',
        name: 'Jascha Krause - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 84,
      },
      {
        type: 'i_45',
        name: 'Joana Neubacher - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 60,
      },
      {
        type: 'i_21',
        name: 'Johannes Gossen - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 91,
      },
      {
        type: 'i_22',
        name: 'Johannes Mang - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 92,
      },
      {
        type: 'i_149',
        name: 'Jonas Klewingha - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 94,
      },
      {
        type: 'i_28',
        name: 'Julia Smuda - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 98,
      },
      {
        type: 'i_29',
        name: 'Julian Derksen - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 99,
      },
      {
        type: 'i_27',
        name: 'Julian Simons - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 100,
      },
      {
        type: 'i_84',
        name: 'Justin Zander - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 101,
      },
    ],
  },
  {
    count: 6,
    Items: [
      {
        type: 'i_83',
        name: 'Karim Boudiaf - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 102,
      },
      {
        type: 'i_26',
        name: 'kathrin Dannert - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 105,
      },
      {
        type: 'i_93',
        name: 'Kevin Kanagaras - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 107,
      },
      {
        type: 'i_178',
        name: 'Kevin Smith - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 235,
      },
      {
        type: 'i_53',
        name: 'Kevin Strewgins - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 108,
      },
      {
        type: 'i_17',
        name: 'Klaus-Georg Pös - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 109,
      },
    ],
  },
  {
    count: 6,
    Items: [
      {
        type: 'i_61',
        name: 'Lea Rees - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 110,
      },
      {
        type: 'i_63',
        name: 'Leah Adolf - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 111,
      },
      {
        type: 'i_57',
        name: 'Lisa Barr - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 114,
      },
      {
        type: 'i_55',
        name: 'Lukas Köster - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 116,
      },
      {
        type: 'i_132',
        name: 'Lydia Dittmann - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 219,
      },
      {
        type: 'i_138',
        name: 'Lydia Doliva - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 222,
      },
    ],
  },
  {
    count: 12,
    Items: [
      {
        type: 'i_58',
        name: 'Manfred Neubach - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 122,
      },
      {
        type: 'i_60',
        name: 'Markus Hagedorn - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 125,
      },
      {
        type: 'i_166',
        name: 'Markus Kurte - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 233,
      },
      {
        type: 'i_129',
        name: 'Martina Hallbau - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 217,
      },
      {
        type: 'i_142',
        name: 'Marusha Ide - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 224,
      },
      {
        type: 'i_101',
        name: 'Max Füllbier - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 207,
      },
      {
        type: 'i_123',
        name: 'Max Voß - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 215,
      },
      { type: 'i_181', name: 'Maya Simons', icon: 'svgCard', hasUser: true, userId: 240 },
      {
        type: 'i_155',
        name: 'Michael Gaidt - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 135,
      },
      {
        type: 'i_102',
        name: 'Mieter1 Eventha - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 206,
      },
      {
        type: 'i_124',
        name: 'Mike Wagenknecht - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 216,
      },
      {
        type: 'i_136',
        name: 'Mirjam Römmelt - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 221,
      },
    ],
  },
  {
    count: 2,
    Items: [
      {
        type: 'i_168',
        name: 'Nicklas Nowottka - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 234,
      },
      {
        type: 'i_158',
        name: 'Niels Neubacher - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 229,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_106',
        name: 'Oliver Paffen - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 209,
      },
    ],
  },
  {
    count: 3,
    Items: [
      {
        type: 'i_62',
        name: 'Patricia Dittma - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 148,
      },
      {
        type: 'i_64',
        name: 'Patrizia Solove - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 149,
      },
      {
        type: 'i_162',
        name: 'Persis Zargari - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 231,
      },
    ],
  },
  {
    count: 3,
    Items: [
      {
        type: 'i_65',
        name: 'Rachel Hellmig - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 150,
      },
      {
        type: 'i_68',
        name: 'Rahel Neubacher - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 151,
      },
      {
        type: 'i_71',
        name: 'Robin Gordziel - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 154,
      },
    ],
  },
  {
    count: 17,
    Items: [
      {
        type: 'i_160',
        name: 'Sabine Fleckhaus - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 230,
      },
      {
        type: 'i_16',
        name: 'Sammy Dittmann - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 161,
      },
      {
        type: 'i_144',
        name: 'Samuel Schwamm - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 225,
      },
      {
        type: 'i_172',
        name: 'Sandra Zayko - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 236,
      },
      {
        type: 'i_70',
        name: 'Sarah Somplatzk - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 162,
      },
      {
        type: 'i_174',
        name: 'Sarina Bijeschke - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 237,
      },
      {
        type: 'i_130',
        name: 'Schuppen links Nutzer - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 218,
      },
      {
        type: 'i_152',
        name: 'Serlin Seliyan - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 227,
      },
      {
        type: 'i_154',
        name: 'Simon Bendig - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 165,
      },
      {
        type: 'i_74',
        name: 'Simon Klement - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 166,
      },
      {
        type: 'i_134',
        name: 'Sonja Brinkmann - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 220,
      },
      {
        type: 'i_19',
        name: 'Sören Koch - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 179,
      },
      {
        type: 'i_72',
        name: 'Steffen Somplat - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 171,
      },
      {
        type: 'i_117',
        name: 'Stephi Piotrowski - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 213,
      },
      {
        type: 'i_69',
        name: 'Susanna Dußler - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 175,
      },
      {
        type: 'i_73',
        name: 'Susanne Bluoss - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 176,
      },
      {
        type: 'i_30',
        name: 'Sylvia Stegeman - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 200,
      },
    ],
  },
  {
    count: 9,
    Items: [
      {
        type: 'i_75',
        name: 'Tabea Korden - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 180,
      },
      {
        type: 'i_76',
        name: 'Tabea Wilson - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 181,
      },
      {
        type: 'i_12',
        name: 'Techniklager einmalgebrauch',
        icon: 'svgPin',
        hasUser: true,
        userId: 198,
      },
      {
        type: 'i_119',
        name: 'Test Aufkleber - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 214,
      },
      {
        type: 'i_120',
        name: 'Test Aufkleber - PIN',
        icon: 'svgPin',
        hasUser: true,
        userId: 214,
      },
      {
        type: 'i_118',
        name: 'Timo Schönig - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 187,
      },
      {
        type: 'i_151',
        name: 'Tina Pöstges',
        icon: 'svgCard',
        hasUser: true,
        userId: 188,
      },
      {
        type: 'i_140',
        name: 'Tobi Graf - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 223,
      },
      {
        type: 'i_77',
        name: 'Tobias Wolff - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 189,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_96',
        name: 'Ulrich Stegeman - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 205,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_176',
        name: 'Vivian von Zelewski - Karte',
        icon: 'svgCard',
        hasUser: true,
        userId: 238,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_78',
        name: 'Yannik Korden - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 196,
      },
    ],
  },
  {
    count: 1,
    Items: [
      {
        type: 'i_23',
        name: 'Zola Plamedi Ma - CARD',
        icon: 'svgCard',
        hasUser: true,
        userId: 88,
      },
    ],
  },
];
